graph TD
    tensorflow
    tensorflow --> absl_py
    tensorflow --> astunparse
    tensorflow --> flatbuffers
    tensorflow --> gast
    tensorflow --> google_pasta
    tensorflow --> libclang
    tensorflow --> opt_einsum
    tensorflow --> packaging
    tensorflow --> protobuf
    tensorflow --> requests
    tensorflow --> setuptools
    tensorflow --> six
    tensorflow --> termcolor
    tensorflow --> typing_extensions
    tensorflow --> wrapt
    tensorflow --> grpcio
    tensorflow --> tensorboard
    tensorflow --> keras
    tensorflow --> numpy
    tensorflow --> h5py
    tensorflow --> ml_dtypes
    tensorflow --> tensorflow_io_gcs_filesystem
    tensorflow --> nvidia_cublas_cu12
    tensorflow --> nvidia_cuda_cupti_cu12
    tensorflow --> nvidia_cuda_nvcc_cu12
    tensorflow --> nvidia_cuda_nvrtc_cu12
    tensorflow --> nvidia_cuda_runtime_cu12
    tensorflow --> nvidia_cudnn_cu12
    tensorflow --> nvidia_cufft_cu12
    tensorflow --> nvidia_curand_cu12
    tensorflow --> nvidia_cusolver_cu12
    tensorflow --> nvidia_cusparse_cu12
    tensorflow --> nvidia_nccl_cu12
    tensorflow --> nvidia_nvjitlink_cu12